name: CI
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  push:
    branches:
      - develop
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - run: echo "🍏 Building the Docker image"
        # env:
        #   DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        #   DOCKER_PASSWORD: ${{ secrets.DOCKER_TOKEN }}
      - name: checkout
        uses: actions/checkout@v4
      - name: login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      - name: build the Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: nguyenhieu198/ecommerce-be:lastest
